# Generated by Django 5.2.7 on 2025-11-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BNFCode",
            fields=[
                ("code", models.TextField(primary_key=True, serialize=False)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Chapter"),
                            (2, "Section"),
                            (3, "Paragraph"),
                            (4, "Subparagraph"),
                            (5, "Chemical Substance"),
                            (6, "Product"),
                            (7, "Presentation"),
                        ]
                    ),
                ),
                ("name", models.TextField()),
            ],
            options={
                "db_table": "bnf_code",
            },
        ),
    ]
