# Generated by Django 5.2.7 on 2025-11-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestedFile",
            fields=[
                ("dataset_name", models.TextField(primary_key=True, serialize=False)),
                ("filename", models.TextField()),
                ("last_modified", models.DateTimeField()),
            ],
            options={
                "db_table": "ingested_file",
            },
        ),
    ]
