# Generated by Django 5.2.8 on 2025-11-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_ingestedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                (
                    "org_type",
                    models.TextField(
                        choices=[
                            ("reg", "Region"),
                            ("icb", "ICB"),
                            ("sic", "SICBL"),
                            ("pcn", "PCN"),
                            ("pra", "Practice"),
                            ("oth", "Other"),
                        ],
                        db_index=True,
                    ),
                ),
                ("name", models.TextField()),
                ("inactive", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "org",
            },
        ),
        migrations.CreateModel(
            name="OrgRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.org",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.org",
                    ),
                ),
            ],
            options={
                "db_table": "org_relation",
            },
        ),
        migrations.AddField(
            model_name="org",
            name="parents",
            field=models.ManyToManyField(
                related_name="children",
                through="data.OrgRelation",
                through_fields=("child", "parent"),
                to="data.org",
            ),
        ),
    ]
