# Generated by Django 6.0.3 on 2026-04-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_org_orgrelation_org_parents"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityRestriction",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "availability_restriction",
            },
        ),
        migrations.CreateModel(
            name="BasisOfName",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "basis_of_name",
            },
        ),
        migrations.CreateModel(
            name="BasisOfStrnth",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "basis_of_strnth",
            },
        ),
        migrations.CreateModel(
            name="Colour",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "colour",
            },
        ),
        migrations.CreateModel(
            name="CombinationPackInd",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "combination_pack_ind",
            },
        ),
        migrations.CreateModel(
            name="CombinationProdInd",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "combination_prod_ind",
            },
        ),
        migrations.CreateModel(
            name="ControlDrugCategory",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "control_drug_category",
            },
        ),
        migrations.CreateModel(
            name="DfIndicator",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "df_indicator",
            },
        ),
        migrations.CreateModel(
            name="DiscontinuedInd",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "discontinued_ind",
            },
        ),
        migrations.CreateModel(
            name="Dnd",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "dnd",
            },
        ),
        migrations.CreateModel(
            name="DtPaymentCategory",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "dt_payment_category",
            },
        ),
        migrations.CreateModel(
            name="Flavour",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "flavour",
            },
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                ("cd", models.BigIntegerField(primary_key=True, serialize=False)),
                ("cddt", models.DateField(null=True)),
                ("cdprev", models.BigIntegerField(null=True)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "form",
            },
        ),
        migrations.CreateModel(
            name="Ing",
            fields=[
                ("isid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("isiddt", models.DateField(null=True)),
                ("isidprev", models.BigIntegerField(null=True)),
                ("invalid", models.BooleanField()),
                ("nm", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "ing",
            },
        ),
        migrations.CreateModel(
            name="LegalCategory",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "legal_category",
            },
        ),
        migrations.CreateModel(
            name="LicensingAuthority",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "licensing_authority",
            },
        ),
        migrations.CreateModel(
            name="LicensingAuthorityChangeReason",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "licensing_authority_change_reason",
            },
        ),
        migrations.CreateModel(
            name="NamechangeReason",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=150, null=True)),
            ],
            options={
                "db_table": "namechange_reason",
            },
        ),
        migrations.CreateModel(
            name="OntFormRoute",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "ont_form_route",
            },
        ),
        migrations.CreateModel(
            name="PriceBasis",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "price_basis",
            },
        ),
        migrations.CreateModel(
            name="ReimbursementStatus",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "reimbursement_status",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("cd", models.BigIntegerField(primary_key=True, serialize=False)),
                ("cddt", models.DateField(null=True)),
                ("cdprev", models.BigIntegerField(null=True)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "route",
            },
        ),
        migrations.CreateModel(
            name="SpecCont",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "spec_cont",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("cd", models.BigIntegerField(primary_key=True, serialize=False)),
                ("cddt", models.DateField(null=True)),
                ("cdprev", models.BigIntegerField(null=True)),
                ("invalid", models.BooleanField()),
                ("descr", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "supplier",
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                ("cd", models.BigIntegerField(primary_key=True, serialize=False)),
                ("cddt", models.DateField(null=True)),
                ("cdprev", models.BigIntegerField(null=True)),
                ("descr", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "unit_of_measure",
            },
        ),
        migrations.CreateModel(
            name="VirtualProductNonAvail",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "virtual_product_non_avail",
            },
        ),
        migrations.CreateModel(
            name="VirtualProductPresStatus",
            fields=[
                ("cd", models.IntegerField(primary_key=True, serialize=False)),
                ("descr", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "virtual_product_pres_status",
            },
        ),
        migrations.CreateModel(
            name="VTM",
            fields=[
                ("vtmid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("invalid", models.BooleanField()),
                ("nm", models.CharField(max_length=255)),
                ("abbrevnm", models.CharField(max_length=60, null=True)),
                ("vtmidprev", models.BigIntegerField(null=True)),
                ("vtmiddt", models.DateField(null=True)),
            ],
            options={
                "db_table": "vtm",
            },
        ),
        migrations.CreateModel(
            name="AMP",
            fields=[
                ("apid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("invalid", models.BooleanField()),
                ("nm", models.CharField(max_length=255)),
                ("abbrevnm", models.CharField(max_length=60, null=True)),
                ("descr", models.CharField(max_length=700)),
                ("nmdt", models.DateField(null=True)),
                ("nm_prev", models.CharField(max_length=255, null=True)),
                ("lic_authchangedt", models.DateField(null=True)),
                ("ema", models.BooleanField()),
                ("parallel_import", models.BooleanField()),
                (
                    "avail_restrict",
                    models.ForeignKey(
                        db_column="avail_restrictcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.availabilityrestriction",
                    ),
                ),
                (
                    "combprod",
                    models.ForeignKey(
                        db_column="combprodcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.combinationprodind",
                    ),
                ),
                (
                    "flavour",
                    models.ForeignKey(
                        db_column="flavourcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.flavour",
                    ),
                ),
                (
                    "lic_auth",
                    models.ForeignKey(
                        db_column="lic_authcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.licensingauthority",
                    ),
                ),
                (
                    "lic_auth_prev",
                    models.ForeignKey(
                        db_column="lic_auth_prevcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.licensingauthority",
                    ),
                ),
                (
                    "lic_authchange",
                    models.ForeignKey(
                        db_column="lic_authchangecd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.licensingauthoritychangereason",
                    ),
                ),
                (
                    "supp",
                    models.ForeignKey(
                        db_column="suppcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "amp",
            },
        ),
        migrations.CreateModel(
            name="ApInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sz_weight", models.CharField(max_length=100, null=True)),
                ("prod_order_no", models.CharField(max_length=20, null=True)),
                (
                    "amp",
                    models.OneToOneField(
                        db_column="apid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.amp",
                    ),
                ),
                (
                    "colour",
                    models.ForeignKey(
                        db_column="colourcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.colour",
                    ),
                ),
            ],
            options={
                "db_table": "ap_info",
            },
        ),
        migrations.CreateModel(
            name="AMPP",
            fields=[
                ("appid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("invalid", models.BooleanField()),
                ("nm", models.CharField(max_length=774)),
                ("abbrevnm", models.CharField(max_length=60, null=True)),
                ("subp", models.CharField(max_length=30, null=True)),
                ("discdt", models.DateField(null=True)),
                (
                    "amp",
                    models.ForeignKey(
                        db_column="apid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.amp",
                    ),
                ),
                (
                    "combpack",
                    models.ForeignKey(
                        db_column="combpackcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.combinationpackind",
                    ),
                ),
                (
                    "disc",
                    models.ForeignKey(
                        db_column="disccd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.discontinuedind",
                    ),
                ),
                (
                    "legal_cat",
                    models.ForeignKey(
                        db_column="legal_catcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.legalcategory",
                    ),
                ),
            ],
            options={
                "db_table": "ampp",
            },
        ),
        migrations.CreateModel(
            name="PrescribInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sched_2", models.BooleanField()),
                ("acbs", models.BooleanField()),
                ("padm", models.BooleanField()),
                ("fp10_mda", models.BooleanField()),
                ("sched_1", models.BooleanField()),
                ("hosp", models.BooleanField()),
                ("nurse_f", models.BooleanField()),
                ("enurse_f", models.BooleanField()),
                ("dent_f", models.BooleanField()),
                (
                    "ampp",
                    models.OneToOneField(
                        db_column="appid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ampp",
                    ),
                ),
            ],
            options={
                "db_table": "prescrib_info",
            },
        ),
        migrations.CreateModel(
            name="PriceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(null=True)),
                ("pricedt", models.DateField(null=True)),
                ("price_prev", models.IntegerField(null=True)),
                (
                    "ampp",
                    models.OneToOneField(
                        db_column="appid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ampp",
                    ),
                ),
                (
                    "price_basis",
                    models.ForeignKey(
                        db_column="price_basiscd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.pricebasis",
                    ),
                ),
            ],
            options={
                "db_table": "price_info",
            },
        ),
        migrations.CreateModel(
            name="PackInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reimb_statdt", models.DateField(null=True)),
                ("pack_order_no", models.CharField(max_length=20, null=True)),
                (
                    "ampp",
                    models.OneToOneField(
                        db_column="appid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ampp",
                    ),
                ),
                (
                    "reimb_stat",
                    models.ForeignKey(
                        db_column="reimb_statcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.reimbursementstatus",
                    ),
                ),
                (
                    "reimb_statprev",
                    models.ForeignKey(
                        db_column="reimb_statprevcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.reimbursementstatus",
                    ),
                ),
            ],
            options={
                "db_table": "pack_info",
            },
        ),
        migrations.CreateModel(
            name="LicRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amp",
                    models.ForeignKey(
                        db_column="apid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.amp",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        db_column="routecd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.route",
                    ),
                ),
            ],
            options={
                "db_table": "lic_route",
            },
        ),
        migrations.CreateModel(
            name="ReimbInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("px_chrgs", models.IntegerField(null=True)),
                ("disp_fees", models.IntegerField(null=True)),
                ("bb", models.BooleanField()),
                ("cal_pack", models.BooleanField()),
                ("fp34d", models.BooleanField()),
                (
                    "ampp",
                    models.OneToOneField(
                        db_column="appid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ampp",
                    ),
                ),
                (
                    "dnd",
                    models.ForeignKey(
                        db_column="dndcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.dnd",
                    ),
                ),
                (
                    "spec_cont",
                    models.ForeignKey(
                        db_column="spec_contcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.speccont",
                    ),
                ),
            ],
            options={
                "db_table": "reimb_info",
            },
        ),
        migrations.CreateModel(
            name="VMP",
            fields=[
                ("vpid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("vpiddt", models.DateField(null=True)),
                ("vpidprev", models.BigIntegerField(null=True)),
                ("invalid", models.BooleanField()),
                ("nm", models.CharField(max_length=255)),
                ("abbrevnm", models.CharField(max_length=60, null=True)),
                ("nmdt", models.DateField(null=True)),
                ("nmprev", models.CharField(max_length=255, null=True)),
                ("sug_f", models.BooleanField()),
                ("glu_f", models.BooleanField()),
                ("pres_f", models.BooleanField()),
                ("cfc_f", models.BooleanField()),
                ("non_availdt", models.DateField(null=True)),
                (
                    "udfs",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "basis",
                    models.ForeignKey(
                        db_column="basiscd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.basisofname",
                    ),
                ),
                (
                    "basis_prev",
                    models.ForeignKey(
                        db_column="basis_prevcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.basisofname",
                    ),
                ),
                (
                    "combprod",
                    models.ForeignKey(
                        db_column="combprodcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.combinationprodind",
                    ),
                ),
                (
                    "df_ind",
                    models.ForeignKey(
                        db_column="df_indcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.dfindicator",
                    ),
                ),
                (
                    "nmchange",
                    models.ForeignKey(
                        db_column="nmchangecd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.namechangereason",
                    ),
                ),
                (
                    "non_avail",
                    models.ForeignKey(
                        db_column="non_availcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.virtualproductnonavail",
                    ),
                ),
                (
                    "pres_stat",
                    models.ForeignKey(
                        db_column="pres_statcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.virtualproductpresstatus",
                    ),
                ),
                (
                    "udfs_uom",
                    models.ForeignKey(
                        db_column="udfs_uomcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.unitofmeasure",
                    ),
                ),
                (
                    "unit_dose_uom",
                    models.ForeignKey(
                        db_column="unit_dose_uomcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.unitofmeasure",
                    ),
                ),
                (
                    "vtm",
                    models.ForeignKey(
                        db_column="vtmid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.vtm",
                    ),
                ),
            ],
            options={
                "db_table": "vmp",
            },
        ),
        migrations.CreateModel(
            name="Ont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        db_column="formcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ontformroute",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        db_column="vpid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.vmp",
                    ),
                ),
            ],
            options={
                "db_table": "ont",
            },
        ),
        migrations.CreateModel(
            name="Droute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        db_column="routecd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.route",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        db_column="vpid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.vmp",
                    ),
                ),
            ],
            options={
                "db_table": "droute",
            },
        ),
        migrations.CreateModel(
            name="Dform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        db_column="formcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.form",
                    ),
                ),
                (
                    "vmp",
                    models.OneToOneField(
                        db_column="vpid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.vmp",
                    ),
                ),
            ],
            options={
                "db_table": "dform",
            },
        ),
        migrations.CreateModel(
            name="ControlInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catdt", models.DateField(null=True)),
                (
                    "cat",
                    models.ForeignKey(
                        db_column="catcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.controldrugcategory",
                    ),
                ),
                (
                    "cat_prev",
                    models.ForeignKey(
                        db_column="cat_prevcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.controldrugcategory",
                    ),
                ),
                (
                    "vmp",
                    models.OneToOneField(
                        db_column="vpid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.vmp",
                    ),
                ),
            ],
            options={
                "db_table": "control_info",
            },
        ),
        migrations.AddField(
            model_name="amp",
            name="vmp",
            field=models.ForeignKey(
                db_column="vpid",
                on_delete=django.db.models.deletion.CASCADE,
                to="data.vmp",
            ),
        ),
        migrations.CreateModel(
            name="VMPP",
            fields=[
                ("vppid", models.BigIntegerField(primary_key=True, serialize=False)),
                ("invalid", models.BooleanField()),
                ("nm", models.CharField(max_length=420)),
                ("abbrevnm", models.CharField(max_length=60, null=True)),
                (
                    "qtyval",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "combpack",
                    models.ForeignKey(
                        db_column="combpackcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.combinationpackind",
                    ),
                ),
                (
                    "qty_uom",
                    models.ForeignKey(
                        db_column="qty_uomcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.unitofmeasure",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        db_column="vpid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.vmp",
                    ),
                ),
            ],
            options={
                "db_table": "vmpp",
            },
        ),
        migrations.CreateModel(
            name="Dtinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(null=True)),
                ("dt", models.DateField(null=True)),
                ("prevprice", models.IntegerField(null=True)),
                (
                    "pay_cat",
                    models.ForeignKey(
                        db_column="pay_catcd",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.dtpaymentcategory",
                    ),
                ),
                (
                    "vmpp",
                    models.OneToOneField(
                        db_column="vppid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.vmpp",
                    ),
                ),
            ],
            options={
                "db_table": "dtinfo",
            },
        ),
        migrations.AddField(
            model_name="ampp",
            name="vmpp",
            field=models.ForeignKey(
                db_column="vppid",
                on_delete=django.db.models.deletion.CASCADE,
                to="data.vmpp",
            ),
        ),
        migrations.CreateModel(
            name="VPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bs_subid", models.BigIntegerField(null=True)),
                (
                    "strnt_nmrtr_val",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "strnt_dnmtr_val",
                    models.DecimalField(decimal_places=3, max_digits=10, null=True),
                ),
                (
                    "basis_strnt",
                    models.ForeignKey(
                        db_column="basis_strntcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.basisofstrnth",
                    ),
                ),
                (
                    "ing",
                    models.ForeignKey(
                        db_column="isid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.ing",
                    ),
                ),
                (
                    "strnt_dnmtr_uom",
                    models.ForeignKey(
                        db_column="strnt_dnmtr_uomcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.unitofmeasure",
                    ),
                ),
                (
                    "strnt_nmrtr_uom",
                    models.ForeignKey(
                        db_column="strnt_nmrtr_uomcd",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="data.unitofmeasure",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        db_column="vpid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.vmp",
                    ),
                ),
            ],
            options={
                "db_table": "vpi",
            },
        ),
    ]
