# Generated by Django 6.0.3 on 2026-04-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0004_availabilityrestriction_basisofname_basisofstrnth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DmdBnfMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dmd_id", models.IntegerField()),
                ("bnf_code", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "dmd_bnf_map",
            },
        ),
    ]
