# Generated by Django 6.0.4 on 2026-05-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0005_dmdbnfmap"),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("vmpp_id", models.IntegerField()),
                ("drug_tariff_category_id", models.IntegerField()),
                ("price_in_pence", models.IntegerField()),
            ],
            options={
                "unique_together": {("date", "vmpp_id")},
            },
        ),
    ]
