# Generated by Django 6.0.4 on 2026-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0006_tariffprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="NCSOConcessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("vmpp", models.IntegerField()),
                ("price_pence", models.IntegerField()),
            ],
            options={
                "unique_together": {("date", "vmpp")},
            },
        ),
    ]
