metadata:
  title: ""
  description: MDIs prescribed as a proportion of all inhalers in BNF Chapter 3, excluding salbutamol
  why_it_matters: <p>The updated <a href='https://www.nice.org.uk/guidance/ng245/chapter/Recommendations#principles-of-pharmacological-treatment' target='_Blank'>BTS/NICE/SIGN guidance on asthma management</a> recommends basing inhaler choice on:<i><ul><li>an assessment of correct technique</li><li>the preference of the person receiving the treatment</li><li>the lowest environmental impact among suitable devices</li><li>the presence of an integral dose counter.</li></ul></i></p><p>The NHS has <a href='https://www.england.nhs.uk/greenernhs/a-net-zero-nhs/' target='_Blank'> committed to reducing its carbon footprint by 80% by 2028 to 2032</a>, including a shift to lower carbon inhalers. Dry powder inhalers (DPIs) and other newer types of inhalers like soft mist inhalers are less harmful to the environment than traditional metered dose inhalers (MDIs). </p><p>The <a href='https://www.england.nhs.uk/long-read/national-medicines-optimisation-opportunities-2023-24/#11-optimising-inhaler-use-to-improve-respiratory-outcomes-and-reduce-carbon-emissions' target='_Blank'>NHS England National Medicines Optimisation Opportunities for 2024/25</a> identify reducing carbon emissions from inhalers as an area for improvement.</p><p><a href='https://www.nice.org.uk/guidance/ng245/resources/patient-decision-aid-on-asthma-inhalers-and-climate-change-bts-nice-sign-pdf-13558151917' target='_Blank'>NICE has produced a inhaler decision aid</a> to facilitiate discussion about inhaler options.</p>
  tags:
    - core
    - greenernhs
    - nice
    - opportunities
    - respiratory
  numerator_short: MDI inhalers (items)
  denominator_short: All inhalers (items)
  authored_by: n/a
  checked_by: n/a
  date_reviewed: n/a
  date_next_review: n/a
output:
  numerator: items
  denominator: items
queries:
  - numerator:
      form_routes:
        - "pressurizedinhalation.inhalation"
      bnf_codes:
        included:
          - "03" # BNF Chapter 3
        excluded:
          - "0301011R0" # Exclude salbutamol
    denominator:
      form_routes: 
        - "pressurizedinhalation.inhalation"
        - "powderinhalation.inhalation"
        - "inhalationsolution.inhalation" 
      bnf_codes:
        included:
          - "03" # BNF Chapter 3  
        excluded:
          - "0301011R0" # Exclude salbutamol    
       
