# This schema describes the structure of the XML files that contain the dm+d data
# published via TRUD.  It was generated by generate_schema.py.
#
# SCHEMA has one entry per data file.  Each entry describes types of data in the
# corresponding file.  Different types of data are grouped together in a single element;
# within the element there is another element for each item in the group.
#
# For instance, the ampp XML file has the following structure:
#
# <?xml version="1.0" encoding="utf-8"?>
# <ACTUAL_MEDICINAL_PROD_PACKS xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ampp_v2_3.xsd">
#   <!-- Generated by NHSBSA PPD -->
#   <AMPPS>
#     <AMPP>
#       <APPID>1327911000001107</APPID>
#       <NM>Verapamil 160mg tablets (A A H Pharmaceuticals Ltd) 56 tablet 4 x 14 tablets</NM>
#       <VPPID>982511000001103</VPPID>
#       <APID>526311000001106</APID>
#       <LEGAL_CATCD>0003</LEGAL_CATCD>
#       <SUBP>4 x 14 tablets</SUBP>
#     </AMPP>
#     <AMPP>...</AMPP>
#     ...
#   </AMPPS>
#   <APPLIANCE_PACK_INFO>
#     <PACK_INFO>
#       <APPID>1383311000001108</APPID>
#       <REIMB_STATCD>0000</REIMB_STATCD>
#     </PACK_INFO>
#     <PACK_INFO>...</PACK_INFO>
#     ...
#   </APPLIANCE_PACK_INFO>
#   ...
#   ...
# </ACTUAL_MEDICINAL_PROD_PACKS>
#
# When there are multiple groups in a file, there is an outer tag -- in this case,
# ACTUAL_MEDICINAL_PROD_PACKS.  When there is only a single group in the file, there is
# no outer tag.
#
# For more information about the meaning of the fields, refer to the documentation at:
#
#     https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/nhs-dictionary-medicines-and-devices-dmd

SCHEMA = {
    "ampp": [
        {
            "group_tag": "AMPPS",
            "item_tag": "AMPP",
            "fields": [
                "APPID",
                "INVALID",
                "NM",
                "ABBREVNM",
                "VPPID",
                "APID",
                "COMBPACKCD",
                "LEGAL_CATCD",
                "SUBP",
                "DISCCD",
                "DISCDT",
            ],
        },
        {
            "group_tag": "APPLIANCE_PACK_INFO",
            "item_tag": "PACK_INFO",
            "fields": [
                "APPID",
                "REIMB_STATCD",
                "REIMB_STATDT",
                "REIMB_STATPREVCD",
                "PACK_ORDER_NO",
            ],
        },
        {
            "group_tag": "DRUG_PRODUCT_PRESCRIB_INFO",
            "item_tag": "PRESCRIB_INFO",
            "fields": [
                "APPID",
                "SCHED_2",
                "ACBS",
                "PADM",
                "FP10_MDA",
                "SCHED_1",
                "HOSP",
                "NURSE_F",
                "ENURSE_F",
                "DENT_F",
            ],
        },
        {
            "group_tag": "MEDICINAL_PRODUCT_PRICE",
            "item_tag": "PRICE_INFO",
            "fields": ["APPID", "PRICE", "PRICEDT", "PRICE_PREV", "PRICE_BASISCD"],
        },
        {
            "group_tag": "REIMBURSEMENT_INFO",
            "item_tag": "REIMB_INFO",
            "fields": [
                "APPID",
                "PX_CHRGS",
                "DISP_FEES",
                "BB",
                "LTD_STAB",
                "CAL_PACK",
                "SPEC_CONTCD",
                "DND",
                "FP34D",
            ],
        },
        {
            "group_tag": "COMB_CONTENT",
            "item_tag": "CCONTENT",
            "fields": ["PRNTAPPID", "CHLDAPPID"],
        },
    ],
    "amp": [
        {
            "group_tag": "AMPS",
            "item_tag": "AMP",
            "fields": [
                "APID",
                "INVALID",
                "VPID",
                "NM",
                "ABBREVNM",
                "DESC",
                "NMDT",
                "NM_PREV",
                "SUPPCD",
                "LIC_AUTHCD",
                "LIC_AUTH_PREVCD",
                "LIC_AUTHCHANGECD",
                "LIC_AUTHCHANGEDT",
                "COMBPRODCD",
                "FLAVOURCD",
                "EMA",
                "PARALLEL_IMPORT",
                "AVAIL_RESTRICTCD",
            ],
        },
        {
            "group_tag": "AP_INGREDIENT",
            "item_tag": "AP_ING",
            "fields": ["APID", "ISID", "STRNTH", "UOMCD"],
        },
        {
            "group_tag": "LICENSED_ROUTE",
            "item_tag": "LIC_ROUTE",
            "fields": ["APID", "ROUTECD"],
        },
        {
            "group_tag": "AP_INFORMATION",
            "item_tag": "AP_INFO",
            "fields": ["APID", "SZ_WEIGHT", "COLOURCD", "PROD_ORDER_NO"],
        },
    ],
    "ingredient": [
        {
            "group_tag": "INGREDIENT_SUBSTANCES",
            "item_tag": "ING",
            "fields": ["ISID", "ISIDDT", "ISIDPREV", "INVALID", "NM"],
        }
    ],
    "lookup": [
        {
            "group_tag": "COMBINATION_PACK_IND",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {
            "group_tag": "COMBINATION_PROD_IND",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {"group_tag": "BASIS_OF_NAME", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {
            "group_tag": "NAMECHANGE_REASON",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {
            "group_tag": "VIRTUAL_PRODUCT_PRES_STATUS",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {
            "group_tag": "CONTROL_DRUG_CATEGORY",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {
            "group_tag": "LICENSING_AUTHORITY",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {
            "group_tag": "UNIT_OF_MEASURE",
            "item_tag": "INFO",
            "fields": ["CD", "CDDT", "CDPREV", "DESC"],
        },
        {
            "group_tag": "FORM",
            "item_tag": "INFO",
            "fields": ["CD", "CDDT", "CDPREV", "DESC"],
        },
        {"group_tag": "ONT_FORM_ROUTE", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {
            "group_tag": "ROUTE",
            "item_tag": "INFO",
            "fields": ["CD", "CDDT", "CDPREV", "DESC"],
        },
        {
            "group_tag": "DT_PAYMENT_CATEGORY",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {
            "group_tag": "SUPPLIER",
            "item_tag": "INFO",
            "fields": ["CD", "CDDT", "CDPREV", "INVALID", "DESC"],
        },
        {"group_tag": "FLAVOUR", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {"group_tag": "COLOUR", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {"group_tag": "BASIS_OF_STRNTH", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {
            "group_tag": "REIMBURSEMENT_STATUS",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {"group_tag": "SPEC_CONT", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {"group_tag": "DND", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {
            "group_tag": "VIRTUAL_PRODUCT_NON_AVAIL",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {"group_tag": "DISCONTINUED_IND", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {"group_tag": "DF_INDICATOR", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {"group_tag": "PRICE_BASIS", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {"group_tag": "LEGAL_CATEGORY", "item_tag": "INFO", "fields": ["CD", "DESC"]},
        {
            "group_tag": "AVAILABILITY_RESTRICTION",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
        {
            "group_tag": "LICENSING_AUTHORITY_CHANGE_REASON",
            "item_tag": "INFO",
            "fields": ["CD", "DESC"],
        },
    ],
    "vmpp": [
        {
            "group_tag": "VMPPS",
            "item_tag": "VMPP",
            "fields": [
                "VPPID",
                "INVALID",
                "NM",
                "ABBREVNM",
                "VPID",
                "QTYVAL",
                "QTY_UOMCD",
                "COMBPACKCD",
            ],
        },
        {
            "group_tag": "DRUG_TARIFF_INFO",
            "item_tag": "DTINFO",
            "fields": ["VPPID", "PAY_CATCD", "PRICE", "DT", "PREVPRICE"],
        },
        {
            "group_tag": "COMB_CONTENT",
            "item_tag": "CCONTENT",
            "fields": ["PRNTVPPID", "CHLDVPPID"],
        },
    ],
    "vmp": [
        {
            "group_tag": "VMPS",
            "item_tag": "VMP",
            "fields": [
                "VPID",
                "VPIDDT",
                "VPIDPREV",
                "VTMID",
                "INVALID",
                "NM",
                "ABBREVNM",
                "BASISCD",
                "NMDT",
                "NMPREV",
                "BASIS_PREVCD",
                "NMCHANGECD",
                "COMBPRODCD",
                "PRES_STATCD",
                "SUG_F",
                "GLU_F",
                "PRES_F",
                "CFC_F",
                "NON_AVAILCD",
                "NON_AVAILDT",
                "DF_INDCD",
                "UDFS",
                "UDFS_UOMCD",
                "UNIT_DOSE_UOMCD",
            ],
        },
        {
            "group_tag": "VIRTUAL_PRODUCT_INGREDIENT",
            "item_tag": "VPI",
            "fields": [
                "VPID",
                "ISID",
                "BASIS_STRNTCD",
                "BS_SUBID",
                "STRNT_NMRTR_VAL",
                "STRNT_NMRTR_UOMCD",
                "STRNT_DNMTR_VAL",
                "STRNT_DNMTR_UOMCD",
            ],
        },
        {"group_tag": "ONT_DRUG_FORM", "item_tag": "ONT", "fields": ["VPID", "FORMCD"]},
        {"group_tag": "DRUG_FORM", "item_tag": "DFORM", "fields": ["VPID", "FORMCD"]},
        {
            "group_tag": "DRUG_ROUTE",
            "item_tag": "DROUTE",
            "fields": ["VPID", "ROUTECD"],
        },
        {
            "group_tag": "CONTROL_DRUG_INFO",
            "item_tag": "CONTROL_INFO",
            "fields": ["VPID", "CATCD", "CATDT", "CAT_PREVCD"],
        },
    ],
    "vtm": [
        {
            "group_tag": "VIRTUAL_THERAPEUTIC_MOIETIES",
            "item_tag": "VTM",
            "fields": ["VTMID", "INVALID", "NM", "ABBREVNM", "VTMIDPREV", "VTMIDDT"],
        }
    ],
}
