"""
Django settings for openprescribing project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


_missing_env_var_hint = """\
If you are running commands locally outside of `just` then you should
make sure that your `.env` file is being loaded into the environment,
which you can do in Bash using:

    set -a; source .env; set +a

If you are seeing this error when running via `just` (which should
automatically load variables from `.env`) then you should check that
`.env` contains all the variables listed in `dotenv-sample` (which may
have been updated since `.env` was first created).

If you are seeing this error in production then you haven't configured
things properly.
"""


def get_env_var(name):
    try:
        return os.environ[name]
    except KeyError:
        raise RuntimeError(
            f"Missing environment variable: {name}\n\n{_missing_env_var_hint}"
        )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]

# Directories for application state. Note that these are not necessarily relative to
# BASE_DIR: if they are absolute paths then they can point anywhere.
DOWNLOAD_DIR = BASE_DIR / get_env_var("OPENPRESCRIBING_DOWNLOAD_DIR")
DATA_DIR = BASE_DIR / get_env_var("OPENPRESCRIBING_DATA_DIR")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = get_env_var("DJANGO_SECRET_KEY")

DEBUG = get_env_var("DJANGO_DEBUG") == "True"

# This is acceptable because nginx is configured to pass requests based on hostname.
ALLOWED_HOSTS = ["*"]

# Very light touch protection of demo site
BASIC_AUTH_USERNAME = os.environ.get("BASIC_AUTH_USERNAME")
BASIC_AUTH_PASSWORD = os.environ.get("BASIC_AUTH_PASSWORD")

# Application definition

INSTALLED_APPS = [
    "openprescribing.web",
    "openprescribing.data",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "openprescribing.web.middleware.BasicAuthMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "openprescribing.web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "openprescribing.config.wsgi.application"


PRESCRIBING_DATABASE = DATA_DIR / "prescribing.duckdb"

SQLITE_DATABASE = DATA_DIR / "data.sqlite"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # This is the database used by the `web` app. We don't expect this to stay on SQLite
    # long term so we don't do any special configuration here.
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_DIR / "web.sqlite",
    },
    # This is the database used by the `data` app
    "data": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": SQLITE_DATABASE,
        "OPTIONS": {
            # For details on these pragmas see: https://www.sqlite.org/pragma.html
            "init_command": """
                /* These settings give much better write performance than the default
                   without sacrificing consistency guarantees */
                PRAGMA journal_mode = WAL;
                PRAGMA synchronous = NORMAL;

                /* Enforce foreign keys which SQLite doesn't do by default only for
                   backwards compatibility reasons */
                PRAGMA foreign_keys = ON;

                /* How long (in ms) to let one write transaction wait for another */
                PRAGMA busy_timeout = 5000;

                /* The default cache size is 2MB but we can afford more! Note negative
                   values set cache size in KB, positive numbers set it by number of
                   database pages */
                PRAGMA cache_size = -256000;
            """,
            # Note we're deliberately not using transaction mode IMMEDIATE here because
            # we're expecting only a single writer and many readers
        },
        # Tell Django's test framework that this database doesn't depend on the default
        # database (which it otherwise assumes that it does)
        "TEST": {"DEPENDENCIES": []},
    },
}


class DatabaseRouter:
    # Read and write queries both use the same logic
    def db_for_read(self, model, **hints):
        return self.db_for_model(model)

    def db_for_write(self, model, **hints):
        return self.db_for_model(model)

    # And that logic is: models belonging to the `data` app go to the `data` db
    def db_for_model(self, model):
        if model._meta.app_label == "data":
            return "data"
        else:  # pragma: no cover
            return "default"

    def allow_migrate(self, db, app_label, model_name=None, **hints):
        if app_label == "data":  # pragma: no branch
            return db == "data"


DATABASE_ROUTERS = [f"{__name__}.DatabaseRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Setting this lets us avoid having to run `collectstatic` for now
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
